In [1]:
import numpy as np

# Creating the array
arr = np.array([[0, 1, 2, 3],
                [4, 5, 6, 7],
                [8, 9, 10, 11]])

print("Original array elements:")
print(arr)

# Multiplying every element by 3
new_arr = arr * 3

print("New array elements:")
print(new_arr)


Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
